services:
  postgres:
    image: postgres
    ports:
      - 5555:5432
    networks:
      - network
    environment:
      POSTGRES_DB: soen363
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    ports:
      - 4444:3500
    networks:
      - network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 3500
    restart: unless-stopped

networks:
  network:
