name: Update GitHub Packages

on:
  push:
    tags:
      - v*

jobs:
  package:
    name: Package the app
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    env:
      GO_VERSION: "1.16.3"

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Use go${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ^${{ env.GO_VERSION }}
      - run: go version

      - name: Build and package
        run: |
          # TODO: Package up the app

  deploy:
    name: Update GitHub Packages
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Deploy to GitHub packages
        run: |
          # TODO: Do the deployment
