name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        required: false
        description: "Test scenario tags"

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["^1.16.3", "1.15", "1.14"]

    steps:
      - uses: actions/checkout@v2
      - name: Use go${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./test/...

  test-yarn:
    name: Yarn Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: ["^15"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd site
          yarn install --dev
          yarn test
          yarn build
          yarn export && rm -rf out/

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test, test-yarn]

    env:
      app-source-name: prepro.go

    strategy:
      matrix:
        go-version: ["^1.16.3", "1.15", "1.14"]

    steps:
      - uses: actions/checkout@v2
      - name: Use go${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go build ${{ env.app-source-name }}
