
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Test scenario tags'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["^1.16.3", "1.15", "1.14"]

    steps:
      - uses: actions/checkout@v2
      - name: Use go${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./test/...

  build:
    name: build
    runs-on: ubuntu-latest
    needs: test

    env:
      app-source-name: prepro.go

    strategy:
      matrix:
        go-version: ["^1.16.3", "1.15", "1.14"]

    steps:
      - uses: actions/checkout@v2
      - name: Use go${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go build ${{ env.app-source-name }}
